version: '3.9'

networks:
    crud:
        driver: bridge
        name: crud

volumes:
    mysql-data:

services:
    server:
        build:
            context: .
            dockerfile: nginx.dockerfile
            args:
                - NGINXUSER=${NGINXUSER:-www-data}
                - NGINXGROUP=${NGINXGROUP:-www-data}
        container_name: crud_nginx
        ports:
            - "80:80"
        volumes:
            -   type: bind
                source: ..
                target: /var/www/html
        depends_on:
            - php
            - mysql
        networks:
            - crud

    mysql:
        image: mysql:8
        container_name: crud_mysql
        restart: unless-stopped
        command: --default-authentication-plugin=caching_sha2_password --max_allowed_packet=3221225472
        tty: true
        ports:
            - "4306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 12345
        networks:
            - crud
        volumes:
            -   type: bind
                source: ./mysql
                target: /docker-entrypoint-initdb.d
            -   type: volume
                source: mysql-data
                target: /var/lib/mysql

    php:
        build:
            context: .
            dockerfile: php.dockerfile
            args:
                - PHPUSER=${PHPUSER:-www-data}
                - PHPGROUP=${PHPGROUP:-www-data}
        container_name: crud_php
        depends_on:
            - mysql
        volumes:
            -   type: bind
                source: ..
                target: /var/www/html
        networks:
            - crud

    node:
        image: node:lts-alpine
        container_name: crud_node
        command: "npm install"
        volumes:
            -   type: bind
                source: ..
                target: /var/www/html
        ports:
            - "3000:3000"
        working_dir: /var/www/html
        networks:
            - crud

#    node:
#        build:
#            context: .
#            dockerfile: node.dockerfile
#        ports:
#            - "3000:3000"
#        container_name: crud_node
#        volumes:
#            -   type: bind
#                source: ..
#                target: /var/www/html
#        networks:
#            - crud

#    artisan:
#        build:
#            context: .
#            dockerfile: php.dockerfile
#            args:
#                - PHPUSER=${PHPUSER:-www-data}
#                - PHPGROUP=${PHPGROUP:-www-data}
#        container_name: crud_artisan
#        volumes:
#            -   type: bind
#                source: ..
#                target: /var/www/html
#        depends_on:
#            - mysql
#        working_dir: /var/www/html
#        entrypoint: [ 'php', '/var/www/html/artisan' ]
#        networks:
#            - crud
#        environment:
#            - COMPOSER_AUTH
